name: dbt CI

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  dbt-build:
    runs-on: ubuntu-latest 

  steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dbt dependencies
      run: |
        pip install --upgrade pip
        pip install dbt-core dbt-postgres

    - name: dbt build
      run: dbt build
      env:
        DBT_PROFILES_DIR: ~/.dbt